apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: europe-docker.pkg.dev/kyma-project/prod/kim-snatch
  newTag: 0.0.4
- name: controller-admission
  newName: IMG=admission-testme
  newTag: latest
