namespace: kyma-system
namePrefix: kim-snatch-

patches:
- path: manager_webhook_patch.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kyma-worker-pool-name=kim-snatch-test
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --webhook-cfg-name=kim-snatch-mutating-webhook-configuration
  target:
    kind: Deployment

resources:
- ../rbac
- ../webhook
- metrics_service.yaml
- ../certmanager
- ../manager

sortOptions:
  order: fifo
